# Generated by Django 5.2.8 on 2025-11-27 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=255, verbose_name='Jméno klienta')),
                ('client_phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon klienta')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail klienta')),
                ('description', models.TextField(blank=True, verbose_name='Poznámka')),
                ('communication_status', models.CharField(choices=[('NEW', 'Nový'), ('IN_CONTACT', 'V kontaktu'), ('MEETING', 'Schůzka domluvena'), ('WON', 'Uzavřeno'), ('LOST', 'Ztraceno')], default='NEW', max_length=32, verbose_name='Stav komunikace')),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Výše provize')),
                ('commission_status', models.CharField(choices=[('NA', 'Nevztahuje se'), ('PENDING', 'Čeká na vyplacení'), ('PAID', 'Vyplaceno'), ('CANCELLED', 'Zrušeno')], default='NA', max_length=32, verbose_name='Stav provize')),
                ('commission_due_date', models.DateField(blank=True, null=True, verbose_name='Termín vyplacení provize')),
                ('advisor', models.ForeignKey(blank=True, help_text='Poradce, který lead obsluhuje.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Poradce')),
                ('referrer', models.ForeignKey(help_text='Kdo tento lead zadal.', on_delete=django.db.models.deletion.PROTECT, related_name='leads_created', to=settings.AUTH_USER_MODEL, verbose_name='Doporučitel (makléř)')),
            ],
        ),
    ]
