# Generated by Django 5.2.8 on 2025-12-04 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Lead založen'), ('NOTE_ADDED', 'Přidána poznámka'), ('UPDATED', 'Lead upraven'), ('MEETING_SCHEDULED', 'Domluvena schůzka'), ('DEAL_CREATED', 'Založen obchod'), ('STATUS_CHANGED', 'Změna stavu')], max_length=32, verbose_name='Typ události')),
                ('description', models.TextField(blank=True, verbose_name='Popis události')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Čas události')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='leads.lead', verbose_name='Lead')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_history_events', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text poznámky')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_notes', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead', verbose_name='Lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
