# Generated by Django 5.2.8 on 2025-12-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_leadhistory_leadnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='communication_status',
            field=models.CharField(choices=[('NEW', 'Nový'), ('MEETING', 'Domluvená schůzka'), ('SEARCHING_PROPERTY', 'Hledá nemovitost'), ('WAITING_FOR_CLIENT', 'Čekání na klienta'), ('FAILED', 'Neúspěšný'), ('DEAL_CREATED', 'Založen obchod'), ('COMMISSION_PAID', 'Provize vyplacena')], default='NEW', max_length=32, verbose_name='Stav komunikace'),
        ),
    ]
