# Generated by Django 5.2.8 on 2025-12-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_communication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='meeting_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datum a čas schůzky'),
        ),
        migrations.AddField(
            model_name='lead',
            name='meeting_note',
            field=models.TextField(blank=True, verbose_name='Poznámka ke schůzce'),
        ),
    ]
