# Generated by Django 5.2.8 on 2025-12-17 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_meeting_at_lead_meeting_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_name', models.CharField(max_length=255, verbose_name='Jméno klienta')),
                ('client_phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon klienta')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail klienta')),
                ('loan_amount', models.PositiveBigIntegerField(verbose_name='Výše úvěru (Kč)')),
                ('bank', models.CharField(choices=[('CS', 'Česká spořitelna'), ('CSOB_HB', 'ČSOB Hypoteční banka'), ('KB', 'Komerční banka'), ('MBANK', 'mBank'), ('OBERBANK', 'Oberbank'), ('RB', 'Raiffeisenbank'), ('UCB', 'Unicredit bank'), ('SSCS', 'Stavební spořitelna České spořitelny'), ('MP', 'Modrá pyramida'), ('CSOB_SS', 'ČSOB stavební spořitelna'), ('RB_SS', 'Raiffeisen stavební spořitelna')], max_length=32, verbose_name='Banka')),
                ('property_type', models.CharField(choices=[('OWN', 'Vlastní'), ('OTHER', 'Cizí')], max_length=16, verbose_name='Nemovitost')),
                ('status', models.CharField(choices=[('REQUEST_IN_BANK', 'Žádost v bance'), ('WAITING_FOR_APPRAISAL', 'Čekání na odhad'), ('PREP_APPROVAL', 'Příprava schvalování'), ('APPROVAL', 'Schvalování'), ('SIGN_PLANNING', 'Plánování podpisu'), ('SIGNED', 'Podepsaná smlouva'), ('SIGNED_NO_PROPERTY', 'Podepsaná smlouva bez nemovitosti'), ('DRAWN', 'Načerpáno')], default='REQUEST_IN_BANK', max_length=32, verbose_name='Stav obchodu')),
                ('commission_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Provize celkem (Kč)')),
                ('commission_referrer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Provize makléř (Kč)')),
                ('commission_manager', models.PositiveIntegerField(blank=True, null=True, verbose_name='Provize manažer (Kč)')),
                ('commission_office', models.PositiveIntegerField(blank=True, null=True, verbose_name='Provize kancelář (Kč)')),
                ('commission_status', models.CharField(choices=[('PENDING', 'Čekání na provizi'), ('READY', 'Provize připravená'), ('PAID', 'Provize vyplacená')], default='PENDING', max_length=16, verbose_name='Stav provize')),
                ('paid_referrer', models.BooleanField(default=False, verbose_name='Vyplacen makléř')),
                ('paid_manager', models.BooleanField(default=False, verbose_name='Vyplacen manažer')),
                ('paid_office', models.BooleanField(default=False, verbose_name='Vyplacena kancelář')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deal', to='leads.lead', verbose_name='Lead')),
            ],
        ),
    ]
