# Generated by Django 5.2.8 on 2025-12-20 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_deal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='meeting_done',
            field=models.BooleanField(default=False, verbose_name='Schůzka proběhla'),
        ),
        migrations.AddField(
            model_name='lead',
            name='meeting_done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Schůzka proběhla (čas)'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['referrer'], name='leads_lead_referre_239cf3_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['advisor'], name='leads_lead_advisor_5ab299_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['communication_status'], name='leads_lead_communi_1bfd14_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['meeting_done'], name='leads_lead_meeting_238c32_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='leads_lead_created_302c6d_idx'),
        ),
    ]
