# Generated by Django 5.2.8 on 2026-01-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_is_personal_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('REQUEST_IN_BANK', 'Žádost v bance'), ('WAITING_FOR_APPRAISAL', 'Čekání na odhad'), ('PREP_APPROVAL', 'Příprava schvalování'), ('APPROVAL', 'Schvalování'), ('SIGN_PLANNING', 'Plánování podpisu'), ('SIGNED', 'Podepsaná smlouva'), ('SIGNED_NO_PROPERTY', 'Podeps. bez nem.'), ('DRAWN', 'Načerpáno'), ('FAILED', 'Neúspěšný')], default='REQUEST_IN_BANK', max_length=32, verbose_name='Stav obchodu'),
        ),
    ]
