# Generated by Django 5.2.8 on 2026-01-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_alter_deal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='callback_note',
            field=models.TextField(blank=True, verbose_name='Poznámka k hovoru'),
        ),
        migrations.AddField(
            model_name='lead',
            name='callback_scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum plánovaného hovoru'),
        ),
    ]
