# Generated by Django 5.2.8 on 2026-01-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_lead_callback_note_lead_callback_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadnote',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Soukromá poznámka'),
        ),
    ]
