# Generated by Django 5.2.8 on 2026-01-16 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_leadnote_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadhistory',
            name='note',
            field=models.ForeignKey(blank=True, help_text='Odkaz na poznámku (pro filtrování soukromých záznamů)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='leads.leadnote', verbose_name='Poznámka'),
        ),
    ]
