# Generated by Django 5.2.8 on 2026-01-20 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_leadhistory_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Čas aktivity')),
                ('activity_type', models.CharField(choices=[('LOGIN', 'Přihlášení'), ('LOGOUT', 'Odhlášení'), ('LEAD_CREATED', 'Lead vytvořen'), ('LEAD_UPDATED', 'Lead upraven'), ('LEAD_NOTE_ADDED', 'Poznámka k leadu přidána'), ('LEAD_CALLBACK_SCHEDULED', 'Odložený hovor naplánován'), ('DEAL_CREATED', 'Obchod vytvořen'), ('DEAL_UPDATED', 'Obchod upraven'), ('DEAL_COMMISSION_READY', 'Provize připravena k vyplacení'), ('DEAL_COMMISSION_PAID', 'Provize vyplacena'), ('OTHER', 'Jiná aktivita')], max_length=32, verbose_name='Typ aktivity')),
                ('description', models.TextField(help_text='Detailní popis co bylo provedeno', verbose_name='Popis aktivity')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP adresa')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Dodatečná data o aktivitě (změněná pole, hodnoty, atd.)', verbose_name='Metadata')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='leads.deal', verbose_name='Obchod')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='leads.lead', verbose_name='Lead')),
                ('user', models.ForeignKey(blank=True, help_text='Uživatel, který provedl akci', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
            ],
            options={
                'verbose_name': 'Log aktivity',
                'verbose_name_plural': 'Logy aktivit',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='leads_activ_timesta_a9ae64_idx'), models.Index(fields=['user', '-timestamp'], name='leads_activ_user_id_1cb1af_idx'), models.Index(fields=['activity_type', '-timestamp'], name='leads_activ_activit_13b99a_idx')],
            },
        ),
    ]
