# Generated by Django 5.2.8 on 2026-01-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_add_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='meeting_scheduled',
            field=models.BooleanField(default=False, help_text='True pokud byla NĚKDY domluvena schůzka (i když nebyla explicitně zaznamenána)', verbose_name='Schůzka byla domluvena'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('LOGIN', 'Přihlášení'), ('LOGOUT', 'Odhlášení'), ('LEAD_CREATED', 'Lead vytvořen'), ('LEAD_UPDATED', 'Lead upraven'), ('LEAD_NOTE_ADDED', 'Poznámka leadu'), ('LEAD_CALLBACK_SCHEDULED', 'Odložený hovor'), ('DEAL_CREATED', 'Obchod vytvořen'), ('DEAL_UPDATED', 'Obchod upraven'), ('DEAL_COMMISSION_READY', 'Provize připravena'), ('DEAL_COMMISSION_PAID', 'Provize vyplacena'), ('OTHER', 'Jiná aktivita')], max_length=32, verbose_name='Typ aktivity'),
        ),
    ]
