# Generated by Django 5.2.8 on 2026-01-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_add_meeting_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='client_first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Křestní jméno klienta'),
        ),
        migrations.AddField(
            model_name='deal',
            name='client_last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Příjmení klienta'),
        ),
        migrations.AddField(
            model_name='lead',
            name='client_first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Křestní jméno klienta'),
        ),
        migrations.AddField(
            model_name='lead',
            name='client_last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Příjmení klienta'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Jméno klienta (legacy)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Jméno klienta (legacy)'),
        ),
    ]
