# Generated by Django 5.2.8 on 2026-01-27 12:36

from django.db import migrations


def migrate_client_names(apps, schema_editor):
    """Zkopíruje existující client_name do client_last_name"""
    Lead = apps.get_model('leads', 'Lead')
    Deal = apps.get_model('leads', 'Deal')

    # Migruj Leady
    for lead in Lead.objects.all():
        if lead.client_name and not lead.client_last_name:
            # Celé jméno dáme do příjmení (referrer obvykle nezná křestní)
            lead.client_last_name = lead.client_name
            lead.save(update_fields=['client_last_name'])

    # Migruj Dealy
    for deal in Deal.objects.all():
        if deal.client_name and not deal.client_last_name:
            # Celé jméno dáme do příjmení
            deal.client_last_name = deal.client_name
            deal.save(update_fields=['client_last_name'])


def reverse_migrate_client_names(apps, schema_editor):
    """Reverse migrace - zkopíruje data zpět"""
    Lead = apps.get_model('leads', 'Lead')
    Deal = apps.get_model('leads', 'Deal')

    # Reverse Leady
    for lead in Lead.objects.all():
        if lead.client_last_name and not lead.client_name:
            if lead.client_first_name:
                lead.client_name = f"{lead.client_last_name} {lead.client_first_name}"
            else:
                lead.client_name = lead.client_last_name
            lead.save(update_fields=['client_name'])

    # Reverse Dealy
    for deal in Deal.objects.all():
        if deal.client_last_name and not deal.client_name:
            if deal.client_first_name:
                deal.client_name = f"{deal.client_last_name} {deal.client_first_name}"
            else:
                deal.client_name = deal.client_last_name
            deal.save(update_fields=['client_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_add_split_name_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_client_names, reverse_migrate_client_names),
    ]
