# Generated by Django 5.2.8 on 2026-01-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_migrate_client_name_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='client_name',
        ),
        migrations.AlterField(
            model_name='deal',
            name='client_last_name',
            field=models.CharField(max_length=255, verbose_name='Příjmení klienta'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='client_last_name',
            field=models.CharField(max_length=255, verbose_name='Příjmení klienta'),
        ),
    ]
