# Generated by Django 5.2.8 on 2025-11-27 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferrerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisors', models.ManyToManyField(blank=True, help_text='Poradci, ze kterých může tento doporučitel vybírat při zakládání leadu.', limit_choices_to={'role': 'ADVISOR'}, related_name='referrers', to=settings.AUTH_USER_MODEL, verbose_name='Přiřazení poradci')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'REFERRER_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_referrers', to=settings.AUTH_USER_MODEL, verbose_name='Manažer doporučitelů')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Doporučitel')),
            ],
        ),
    ]
