# Generated by Django 5.2.8 on 2025-12-04 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_referrerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrerprofile',
            name='last_chosen_advisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_referrers', to=settings.AUTH_USER_MODEL, verbose_name='Naposledy zvolený poradce'),
        ),
    ]
