# Generated by Django 5.2.8 on 2025-12-10 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_referrerprofile_last_chosen_advisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ADVISOR', 'Poradce'), ('REFERRER', 'Doporučitel'), ('REFERRER_MANAGER', 'Manažer doporučitelů'), ('OFFICE', 'Kancelář')], default='REFERRER', help_text='Role uživatele v systému LeadBridge.', max_length=32),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Název kanceláře')),
                ('owner', models.ForeignKey(blank=True, limit_choices_to={'role': 'OFFICE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_offices', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel kanceláře')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'REFERRER_MANAGER'}, on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL, verbose_name='Manažer')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='accounts.office', verbose_name='Kancelář')),
            ],
        ),
    ]
