# Generated by Django 5.2.8 on 2026-01-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role_office_managerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefonní číslo uživatele.', max_length=20, verbose_name='Telefon'),
        ),
    ]
