# Generated by Django 5.2.8 on 2026-01-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Procento z celkové provize, na které má uživatel nárok (např. 50.00 pro 50%).', max_digits=5, verbose_name='Procento z celkové provize'),
        ),
        migrations.AddField(
            model_name='user',
            name='commission_total_per_million',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Celková provize za každý 1 000 000 Kč realizované hypotéky (např. 7000).', max_digits=10, verbose_name='Celková provize za 1 mil. Kč'),
        ),
    ]
