# Generated by Django 5.2.8 on 2026-01-07 09:40

from django.db import migrations, models


def migrate_commission_data(apps, schema_editor):
    """Zkopíruje data z commission_percentage do commission_referrer_pct"""
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        user.commission_referrer_pct = user.commission_percentage
        user.save(update_fields=['commission_referrer_pct'])


def reverse_migrate_commission_data(apps, schema_editor):
    """Zkopíruje zpět data z commission_referrer_pct do commission_percentage"""
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        user.commission_percentage = user.commission_referrer_pct
        user.save(update_fields=['commission_percentage'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_commission_percentage_and_more'),
    ]

    operations = [
        # 1. Přidat nová pole
        migrations.AddField(
            model_name='user',
            name='commission_referrer_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Procento z celkové provize pro doporučitele (např. 90.00 pro 90%).', max_digits=5, verbose_name='Procento provize doporučitele'),
        ),
        migrations.AddField(
            model_name='user',
            name='commission_manager_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Procento z celkové provize pro manažera (např. 10.00 pro 10%).', max_digits=5, verbose_name='Procento provize manažera'),
        ),
        migrations.AddField(
            model_name='user',
            name='commission_office_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Procento z celkové provize pro kancelář (např. 40.00 pro 40%).', max_digits=5, verbose_name='Procento provize kanceláře'),
        ),
        # 2. Zkopírovat data
        migrations.RunPython(migrate_commission_data, reverse_migrate_commission_data),
        # 3. Odstranit staré pole
        migrations.RemoveField(
            model_name='user',
            name='commission_percentage',
        ),
    ]
