# Generated by Django 5.2.8 on 2026-01-07 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_commission_fields_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_admin_access',
            field=models.BooleanField(default=False, help_text='Poradce s administrativním přístupem vidí leady a obchody všech svých podřízených doporučitelů.', verbose_name='Administrativní přístup'),
        ),
        migrations.AlterField(
            model_name='referrerprofile',
            name='user',
            field=models.OneToOneField(help_text='Uživatel, který může vystupovat jako doporučitel (makléř, manažer, kancelář)', on_delete=django.db.models.deletion.CASCADE, related_name='referrer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Doporučitel'),
        ),
    ]
