# Generated by Django 5.2.8 on 2026-01-07 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_make_name_fields_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrerprofile',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Manažer nebo kancelář, pod kterého tento doporučitel spadá.', limit_choices_to={'role__in': ['REFERRER_MANAGER', 'OFFICE']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_referrers', to=settings.AUTH_USER_MODEL, verbose_name='Manažer doporučitelů'),
        ),
    ]
