# Generated by Django 5.2.8 on 2026-01-09 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_allow_office_as_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_color', models.CharField(default='#1F6F7A', help_text='Hex kód barvy pro tmavou část navbaru (např. #1F6F7A).', max_length=7, verbose_name='Barva navbaru')),
                ('navbar_text_color', models.CharField(default='#FFFFFF', help_text='Hex kód barvy pro text v navbaru (např. #FFFFFF pro bílou).', max_length=7, verbose_name='Barva textu v navbaru')),
                ('logo', models.ImageField(blank=True, help_text='Vlastní logo, které se zobrazí místo defaultního LeadBridge loga.', null=True, upload_to='branding/logos/', verbose_name='Vlastní logo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizováno')),
                ('owner', models.OneToOneField(help_text='Advisor s administrativním přístupem, který může upravovat branding pro svůj tým.', limit_choices_to={'has_admin_access': True, 'role': 'ADVISOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='branding_settings', to=settings.AUTH_USER_MODEL, verbose_name='Vlastník brandingu')),
            ],
            options={
                'verbose_name': 'Nastavení brandingu',
                'verbose_name_plural': 'Nastavení brandingu',
            },
        ),
    ]
