# Generated by Django 5.2.8 on 2026-01-15 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_fix_referrer_advisors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role__in': ['REFERRER_MANAGER', 'OFFICE']}, on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL, verbose_name='Manažer'),
        ),
    ]
