# Generated by Django 5.2.8 on 2026-01-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_managerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='advisor_commission_per_million',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Provize poradce za každý 1 000 000 Kč realizované hypotéky (např. 15500). Tato provize je nad rámec provizí struktury.', max_digits=10, verbose_name='Provize poradce za 1 mil. Kč'),
        ),
    ]
