# Generated by Django 5.2.8 on 2026-01-17 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_advisor_commission_per_million'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='advisor_commission_own_deals',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Provize za vlastní kontakty bez struktury (např. 12000)', max_digits=10, verbose_name='Provize za vlastní obchody (Typ 2)'),
        ),
        migrations.AddField(
            model_name='user',
            name='advisor_commission_structure_deals',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Provize za obchody přes makléře (např. 6480)', max_digits=10, verbose_name='Provize za obchody se strukturou (Typ 2)'),
        ),
        migrations.AddField(
            model_name='user',
            name='advisor_commission_type',
            field=models.CharField(choices=[('FULL_MINUS', 'Typ 1: Plná provize - platí strukturu sám'), ('NET_STRUCT', 'Typ 2: Čistá provize (struktura zvlášť)')], default='FULL_MINUS', help_text='Jak se počítá provize poradce za jeho obchody', max_length=20, verbose_name='Typ provizního modelu'),
        ),
        migrations.AddField(
            model_name='user',
            name='advisor_manager',
            field=models.ForeignKey(blank=True, help_text='Poradce s admin přístupem, který dostává meziprovizi za obchody tohoto poradce', limit_choices_to={'has_admin_access': True, 'role': 'ADVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_advisors', to=settings.AUTH_USER_MODEL, verbose_name='Nadřízený poradce (manažer)'),
        ),
        migrations.AddField(
            model_name='user',
            name='advisor_manager_commission_own_deals',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Meziprovize za vlastní kontakty podřízených poradců (např. 3500)', max_digits=10, verbose_name='Meziprovize za vlastní obchody podřízených (Typ 3)'),
        ),
        migrations.AddField(
            model_name='user',
            name='advisor_manager_commission_structure_deals',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Meziprovize za obchody podřízených přes makléře (např. 2000)', max_digits=10, verbose_name='Meziprovize za obchody se strukturou (Typ 3)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='advisor_commission_per_million',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Plná provize od banky (např. 15500). Struktura se odečítá.', max_digits=10, verbose_name='Provize poradce za 1 mil. Kč (Typ 1)'),
        ),
    ]
