# Generated by Django 5.2.8 on 2026-01-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_advisor_commission_own_deals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='advisor_manager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='advisor_manager_commission_own_deals',
        ),
        migrations.RemoveField(
            model_name='user',
            name='advisor_manager_commission_structure_deals',
        ),
    ]
